### PR TITLE
Level manager2 - Can know total pickups & broadcast victory!

### PR DESCRIPTION
**Pull request by QatariGameDev**
Level manager2 - Can know total pickups & broadcast victory!

### CODE REVIEW

**Comment by WingBytePX** [comment]
Hi @QatariGameDev 
I get this error when I start the level
image
and this when I called the objects
image
is it ok?


Also, which folder structure should we follow in this project?
scripts in one folder and the scenes in another folder?
or
Entity-based folder structure (every game object is encapsulated in a single folder)?

**Comment by QatariGameDev** [comment]
Hi @WingBytePX 

I should mention that OneDrive caused some issues earlier this morning, and I was worried it might have affected the project. Therefore, I am anticipating some regression in this respect.

Additionally, Godot has some problems with file names when working with source control and more then one person..

 > Also, which folder structure should we follow in this project?
scripts in one folder and the scenes in another folder?
or
Entity-based folder structure (every game object is encapsulated in a single folder)?

I prefer to keep scripts in one folder and images in another for the sake of organization. 

However, it should be noted that according to the Godot Team, an entity-based folder structure can provide a slight performance boost and speed up resource loading. But since our game project is very simple, I believe we'll be fine as is.

**Comment by WingBytePX** [comment]
@QatariGameDev No problem.

As for the names, I remember if we worked on completing separate scenes we shouldn't face any problems. Did something change?

And for the folder structure, ok I will update mine later as separate the scripts from the scenes.

**Comment by QatariGameDev** [comment]
> @QatariGameDev No problem.
> 
> As for the names, I remember if we worked on completing separate scenes we shouldn't face any problems. Did something change?
> 
> And for the folder structure, ok I will update mine later as separate the scripts from the scenes.

Hi @WingBytePX 

I must stress that OneDrive has repeatedly misplaced my files without my permission, corrupting them including the game project. 

Additionally, issues with my QatariDev account led me to commit directly to the master branch by mistake yesterday. 

To avoid further problems in future, I redownloaded the project and made new local changes to prevent any caching errors or bug regressions.

**Comment by WingBytePX** [comment]
Hi again @QatariGameDev ,

Is it better to wait for you to push again? or should I continue normally?
Because right now, my 2 remaining tasks are almost part of what you have already implemented.

Also, I can't reorganize the script files; otherwise, it might cause conflict with your branch.

**Comment by QatariGameDev** [comment]
Hi @WingBytePX 

I'm currently fixing the errors you have mentioned before pushing to the branch again. 

At this stage, let's keep everything regarding the files structures as-is to complete the MVP.

**Comment by WingBytePX** [comment]
Ok good.

**Comment by QatariGameDev** [comment]
Hi @WingBytePX 
I fixed the issues, i will create a new pull request.

**Pull request closed without merging**
